export const candidates = [
  {
    id: 1,
    imgSrc: '/candidates/이재명.png',
    name: '이재명',
    party: '더불어 민주당',
    slogan: '이제부터 진짜 대한민국',
    colorClassName: 'bg-democratic',
  },
  {
    id: 2,
    imgSrc: '/candidates/김문수.png',
    name: '김문수',
    party: '국민의 힘',
    slogan: '새롭게 앞으로 위대한 대한민국',
    colorClassName: 'bg-people',
  },
  {
    id: 3,
    imgSrc: '/candidates/이준석.png',
    name: '이준석',
    party: '개혁신당',
    slogan: '미래를 여는 선택, 새로운 대통령',
    colorClassName: 'bg-reform',
  },
  {
    id: 4,
    imgSrc: '/candidates/권영국.png',
    name: '권영국',
    party: '민주노동당',
    slogan: '갈아엎자! 불평등 세상',
    colorClassName: 'bg-labor',
  },
  // {
  //   id: 5,
  //   imgSrc: '/candidates/구주와.png',
  //   name: '구주와',
  //   party: '자유통일당',
  //   slogan: '광화문 정신! 정치 교체!',
  //   colorClassName: 'bg-free',
  // },
  {
    id: 6,
    imgSrc: '/candidates/황교안.png',
    name: '황교안',
    party: '무소속',
    slogan: '부정선거 척결로 청년에게 미래를',
    colorClassName: 'bg-independent1',
  },
  {
    id: 7,
    imgSrc: '/candidates/송진호.png',
    name: '송진호',
    party: '무소속',
    slogan: '선경제, 후정치!',
    colorClassName: 'bg-independent2',
  },
];
